"""empty message

Revision ID: ced470ce82f6
Revises: 1fdd6168e2d0
Create Date: 2023-08-23 16:09:27.229970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced470ce82f6'
down_revision = '1fdd6168e2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
