"""empty message

Revision ID: ced470ce82f6
Revises: 1fdd6168e2d0
Create Date: 2023-08-23 16:09:27.229970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced470ce82f6'
down_revision = '1fdd6168e2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'price',
                    existing_type=sa.REAL,
                    type_=sa.Float(precision=2),
                    existing_nullable=False)
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=80),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users','password',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=80),
                    existing_nullable=False)
    op.alter_column('items','price',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=False)
    # ### end Alembic commands ###
